### ISSUE TITLE
[1.20.4] [All] Exception when removing duplicates modules on windows

### ISSUE THREAD

**Issue by emyfops** [architectury/architectury-transformer#24]
Recently, a new error arose on Architectury transformer 5.2.87
The suspected commit is b79d342, this is the one that introduced the method to remove duplicate modules on `SecureModuleFinder`

Full stacktrace https://mclo.gs/jiHmNgx

Additional info:
- Forge 49.1.4
- Architectury Loom 1.7.412
- Java 17
- Windows 10

**Comment by emyfops** [comment]
The issue is actually caused by the OS path separator
On linux the separator is `/` whereas windows has `\\`

**Comment by Userhunt** [comment]
Same for fabric
